export const category = {
  recommend: {
    categories: [
      {
        id: "SC_strongsmell",
        name: "smellCode",
        value: "001",
        text: "#냄새 강한",
        type: "radio",
      },
      {
        id: "SC_middlesmell",
        name: "smellCode",
        value: "002",
        text: "#냄새 중간",
        type: "radio",
      },
      {
        id: "SC_rowsmell",
        name: "smellCode",
        value: "003",
        text: "#냄새 약한",
        type: "radio",
      },
      {
        id: "SC_nonesmell",
        name: "smellCode",
        value: "004",
        text: "#냄새 거의없음",
        type: "radio",
      },
      {
        id: "SC_beginners",
        name: "managelevelCode",
        value: "001",
        text: "#초보자용",
        type: "radio",
      },
      {
        id: "SC_advanced",
        name: "managelevelCode",
        value: "002",
        text: "#경험자용",
        type: "radio",
      },
      {
        id: "SC_expert",
        name: "managelevelCode",
        value: "003",
        text: "#전문가용",
        type: "radio",
      },
      {
        id: "SC_shrub01",
        name: "grwhstleCodeNmArr",
        value: "직립형",
        text: "#직립형",
        type: "checkbox",
      },
      {
        id: "SC_shrub02",
        name: "grwhstleCodeNmArr",
        value: "관목형",
        text: "#관목형",
        type: "checkbox",
      },
      {
        id: "SC_shrub03",
        name: "grwhstleCodeNmArr",
        value: "덩굴성",
        text: "#덩굴성",
        type: "checkbox",
      },
      {
        id: "SC_shrub04",
        name: "grwhstleCodeNmArr",
        value: "풀모양",
        text: "#풀모양",
        type: "checkbox",
      },
      {
        id: "SC_shrub05",
        name: "grwhstleCodeNmArr",
        value: "로제트형",
        text: "#로제트형",
        type: "checkbox",
      },
      {
        id: "SC_shrub06",
        name: "grwhstleCodeNmArr",
        value: "다육형",
        text: "#다육형",
        type: "checkbox",
      },
    ],
  },
  buy: {
    categories: [
      {
        id: "SC_strongsmell",
        name: "smellCode",
        value: "001",
        text: "#냄새 강한",
        type: "radio",
      },
      {
        id: "SC_middlesmell",
        name: "smellCode",
        value: "002",
        text: "#냄새 중간",
        type: "radio",
      },
      {
        id: "SC_rowsmell",
        name: "smellCode",
        value: "003",
        text: "#냄새 약한",
        type: "radio",
      },
      {
        id: "SC_nonesmell",
        name: "smellCode",
        value: "004",
        text: "#냄새 거의없음",
        type: "radio",
      },
      {
        id: "SC_beginners",
        name: "managelevelCode",
        value: "001",
        text: "#초보자용",
        type: "radio",
      },
      {
        id: "SC_advanced",
        name: "managelevelCode",
        value: "002",
        text: "#경험자용",
        type: "radio",
      },
      {
        id: "SC_expert",
        name: "managelevelCode",
        value: "003",
        text: "#전문가용",
        type: "radio",
      },
      {
        id: "SC_shrub01",
        name: "grwhstleCodeNmArr",
        value: "직립형",
        text: "#직립형",
        type: "checkbox",
      },
      {
        id: "SC_shrub02",
        name: "grwhstleCodeNmArr",
        value: "관목형",
        text: "#관목형",
        type: "checkbox",
      },
      {
        id: "SC_shrub03",
        name: "grwhstleCodeNmArr",
        value: "덩굴성",
        text: "#덩굴성",
        type: "checkbox",
      },
      {
        id: "SC_shrub04",
        name: "grwhstleCodeNmArr",
        value: "풀모양",
        text: "#풀모양",
        type: "checkbox",
      },
      {
        id: "SC_shrub05",
        name: "grwhstleCodeNmArr",
        value: "로제트형",
        text: "#로제트형",
        type: "checkbox",
      },
      {
        id: "SC_shrub06",
        name: "grwhstleCodeNmArr",
        value: "다육형",
        text: "#다육형",
        type: "checkbox",
      },
    ],
  },
};
